# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actstream', '0003_auto_20160528_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
