# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 22:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('actstream', '0004_action_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='deleted',
        ),
        migrations.AlterField(
            model_name='action',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
